version: '3'
services:
  
  actix:
    build: actix
    image: welfade-actix
    tty: true
    volumes:
      - ../backend:/actix
    ports:
      - 3000:80
    depends_on:
      - postgres
    command: cargo watch -x run

  postgres:
    build: postgres
    image: welfade-postgres
    volumes:
      # コンテナの `/var/lib/postgresql/data` を、volume `welfade-data` にマウントする。
      - "welfade-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: welfade
      POSTGRES_USER: welfade
      POSTGRES_PASSWORD: password
  vue:
    build: ./vue # dockerfileの場所
    ports:
      - 8080:8080
    command: yarn serve
    volumes: # ホスト共有フォルダ : ゲスト共有フォルダ
      - ../frontend:/vue
      - node_modules:/vue/node_modules

      # volumes を定義する
volumes:
  # volume の名前を指定
  welfade-data:
  node_modules:
    # Compose の外ですでに作成済みの volume を指定する場合は ture を設定する。
    # そうすると、 docker-compose up 時に Compose は volume を作成しようとしません。
    # かつ、指定した volume が存在しないとエラーを raise します。
    # external: true